exporter.baseDirectory = ./output/
exporter.pretty_print = true
# set years_of_history = 0 to skip filtering altogether and keep the entire history
exporter.years_of_history = 10

# the number of patients to generate, by default
# this can be overridden by passing a different value to the Generator constructor
# Number corresponds to number of LIVING patients, so total generation may be higher
generate.default_population = 3

#for MVP, just use simple CSV export
exporter.fhir.export = true
# exporter.fhir.use_us_core_ig = true
# exporter.fhir.us_core_version = 6.1.0
# exporter.fhir.transaction_bundle = true

# settings for specifying FHIR resources, see example usage in synthea/deafult_settings.properties
# exporter.fhir.included_resources =
# exporter.fhir.excluded_resources =

exporter.metadata.export = true
exporter.csv.export = true
# if exporter.csv.append_mode = true, then each run will add new data to any existing CSVs. 
# if false, each run will clear out the files and start fresh
exporter.csv.append_mode = false
# if exporter.csv.folder_per_run = true, then each run will have CSVs placed into a unique subfolder. 
# if false, each run will only use the top-level csv folder
exporter.csv.folder_per_run = false
exporter.encoding = UTF-8
exporter.json.export = false
# included_files and excluded_files list out the files to include/exclude in the csv exporter
# only one of these may be set at a time, if both are set then both will be ignored
# if neither is set, then all files will be included
# see list of files at: https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary
# include filenames separated with a comma, ex: patients.csv,procedures.csv,medications.csv
# NOTE: the csv exporter does not actively delete files, so if Run 1 you included a file, 
# then Run 2 you exclude that file, the version from Run 1 will still be present
# exporter.csv.included_files = 
# Don't need insurance/payment info for MVP
exporter.csv.excluded_files = claims.csv, claims_transactions.csv, patient_expenses.csv, imaging_studies.csv, organizations.csv, payer_transitions.csv, payers.csv, providers.csv, supplies.csv

# Not positive what symptoms export settings entail, but will probably be useful for full project
# parameters for symptoms export
exporter.symptoms.csv.export = false
# selection mode of conditions or symptom export: 0 = conditions according to  exporter.years_of_history. other values = all conditions (entire history)
exporter.symptoms.mode = 0

# Lookup Table Folder location
# Not sure what this does currently
generate.lookup_tables = modules/lookup_tables/

# default demographics is every city in the US
#for now, I want to use houston demographics, I will simply use the info from the synthea provided resources
generate.demographics.default_file = geography/demographics.csv
generate.geography.zipcodes.default_file = geography/zipcodes.csv
generate.geography.country_code = US
generate.geography.timezones.default_file = geography/timezones.csv
generate.geography.foreign.birthplace.default_file = geography/foreign_birthplace.json
generate.geography.sdoh.default_file = geography/sdoh.csv
# https://terminology.hl7.org/identifiers.html
generate.geography.passport_uri = http://hl7.org/fhir/sid/passport-USA

# Providers (synthea resources)
generate.providers.hospitals.default_file = providers/hospitals.csv
generate.providers.longterm.default_file = providers/longterm.csv
generate.providers.nursing.default_file = providers/nursing.csv
generate.providers.rehab.default_file = providers/rehab.csv
generate.providers.hospice.default_file = providers/hospice.csv
generate.providers.dialysis.default_file = providers/dialysis.csv
generate.providers.homehealth.default_file = providers/home_health_agencies.csv
generate.providers.veterans.default_file = providers/va_facilities.csv
generate.providers.urgentcare.default_file = providers/urgent_care_facilities.csv
generate.providers.primarycare.default_file = providers/primary_care_facilities.csv
generate.providers.ihs.hospitals.default_file = providers/ihs_facilities.csv
generate.providers.ihs.primarycare.default_file = providers/ihs_centers.csv